#!/bin/bash

host="${1:-localhost}"
port="${2:-9090}"

for i in 0 1 2 3 4 5 6 7 8 9
do
	curl -i -H "Accept: application/json" -X PUT http://$host:$port/jee6webapp/resources/appuser/create/user$i/password$i
	echo ""
done

curl -i -H "Accept: application/json" -X GET http://$host:$port/jee6webapp/resources/appuser
echo ""


while read a b c d e f g h
do
	if [ -n "$h" ]
	then
		echo $h
		echo ""
		curl -X PUT --data-binary "{ \"name\":\"$h\" }" -H "Content-Type: application/json" -H "Accept: application/json" http://$host:$port/jee6webapp/resources/artist -v
		echo ""
	fi
done < <(ls -l /home/*/QNAP/Public/Freecom400GB/jukebox/playlist)

curl -i -H "Accept: application/json" -X GET http://$host:$port/jee6webapp/resources/artist
echo ""

while read a b c d e f g h
do
	if [ -n "$h" ]
	then
		echo $h
		echo ""
		curl -X PUT --data-binary "{ \"name\":\"$h\" }" -H "Content-Type: application/json" -H "Accept: application/json" http://$host:$port/jee6webapp/resources/album -v
		echo ""
	fi
done < <(ls -l /home/*/QNAP/Public/Freecom400GB/jukebox/playlist/*)

curl -i -H "Accept: application/json" -X GET http://$host:$port/jee6webapp/resources/album
echo ""

while read a b c d e f g h
do
	if [ -n "$h" ]
	then
		echo $h
		echo ""
		curl -X PUT --data-binary "{ \"name\":\"$h\" }" -H "Content-Type: application/json" -H "Accept: application/json" http://$host:$port/jee6webapp/resources/track -v
		echo ""
	fi
done < <(ls -l /home/*/QNAP/Public/Freecom400GB/jukebox/playlist/*/*)

curl -i -H "Accept: application/json" -X GET http://$host:$port/jee6webapp/resources/track
echo ""

