#!/bin/bash

host="${1:-localhost}"
port="${2:-9090}"

for i in 0 1 2 3 4 5 6 7 8 9
do
	curl -X POST --data-binary "{\"username\":\"user$i\",\"password\":\"password$i\"}" -H "Content-Type: application/json" -H "Accept: application/json" http://$host:$port/jee6webapp/resources/appuser
	echo ""
done
curl -i -H "Accept: application/json" -X GET http://$host:$port/jee6webapp/resources/appuser
echo ""

while read a b c d e f g h
do
	if [ -n "$h" ]
	then
		curl -X POST --data-binary "{\"name\":\"$h\"}" -H "Content-Type: application/json" -H "Accept: application/json" http://$host:$port/jee6webapp/resources/artist
		echo ""
	fi
done < <(ls -l /home/*/QNAP/Public/Freecom400GB/jukebox/playlist)
curl -i -H "Accept: application/json" -X GET http://$host:$port/jee6webapp/resources/artist
echo ""

while read a b c d e f g h
do
	if [ -n "$h" ]
	then
		curl -X POST --data-binary "{\"name\":\"$h\"}" -H "Content-Type: application/json" -H "Accept: application/json" http://$host:$port/jee6webapp/resources/album
		echo ""
	fi
done < <(ls -l /home/*/QNAP/Public/Freecom400GB/jukebox/playlist/*)
curl -i -H "Accept: application/json" -X GET http://$host:$port/jee6webapp/resources/album
echo ""

while read a b c d e f g h
do
	if [ -n "$h" ]
	then
		curl -X POST --data-binary "{\"name\":\"$h\"}" -H "Content-Type: application/json" -H "Accept: application/json" http://$host:$port/jee6webapp/resources/track
		echo ""
	fi
done < <(ls -l /home/*/QNAP/Public/Freecom400GB/jukebox/playlist/*/*)
curl -i -H "Accept: application/json" -X GET http://$host:$port/jee6webapp/resources/track
echo ""

exit 0

curl -X GET -H "Accept: application/json" http://localhost:9090/jee6webapp/resources/artist

curl -X POST --data-binary "{\"name\":\"XXXXX\",\"url\":\"http://doitto.me.uk\",\"duration\":\"210\"}" -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:9090/jee6webapp/resources/track

curl -X PUT --data-binary "{\"name\":\"XXZXX\",\"url\":\"YYYYY\",\"duration\":\"210\"}" -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:9090/jee6webapp/resources/track/1

